# Generated by Django 5.1.1 on 2025-04-17 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="lastname",
        ),
    ]
