# Generated by Django 5.1.7 on 2025-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0002_appuser_firstname_appuser_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
