# Generated by Django 5.2 on 2025-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0002_remove_appuser_firstname_remove_appuser_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=1000),
        ),
    ]
