# Generated by Django 5.1.1 on 2025-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0003_alter_appuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profilePicture.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
