# Generated by Django 5.1.1 on 2025-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0004_alter_appuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
