# Generated by Django 5.2 on 2025-04-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='content',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=100),
        ),
    ]
