# Generated by Django 5.2 on 2025-04-19 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userSkills", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userskills",
            unique_together=set(),
        ),
    ]
